### ISSUE TITLE
你好，可否在readme里完善一下最终小程序开发出来的页面或者功能，以图片或者视频的方式进行演示呢？感谢

### ISSUE THREAD

**Issue by aitaiyangdemao** [smilelight/todolist#1]

**Comment by smilelight** [comment]
@aitaiyangdemao 你好，这个是我将近一年前搞的了，当时也不太会用Github，现在电脑都换了，也不从事微信小程序开发的相关工作了，所以暂时不考虑提供了哈，实在是抱歉了。

**Comment by smilelight** [comment]
@aitaiyangdemao 抱歉，现在重新整理了一下，已经更新至README了。
